version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 4
  ignore:
  - dependency-name: cypress
    versions:
    - 6.3.0
    - 6.4.0
    - 6.5.0
    - 6.6.0
    - 6.7.0
    - 6.7.1
    - 6.8.0
    - 7.0.0
    - 7.0.1
    - 7.1.0
  - dependency-name: "@cypress/code-coverage"
    versions:
    - 3.9.3
  - dependency-name: chai
    versions:
    - 4.3.2
- package-ecosystem: npm
  directory: "/frontend"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 4
  ignore:
  - dependency-name: react-hook-form
    versions:
    - "> 6.4.1"
  - dependency-name: react-map-gl
    versions:
    - 5.3.1
    - 6.1.0
    - 6.1.1
    - 6.1.10
    - 6.1.11
    - 6.1.2
    - 6.1.3
    - 6.1.4
    - 6.1.5
    - 6.1.6
    - 6.1.7
    - 6.1.8
    - 6.1.9
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
- package-ecosystem: npm
  directory: "/backend"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 4
  ignore:
  - dependency-name: sinon
    versions:
    - 10.0.0
  - dependency-name: connect-mongo
    versions:
    - 4.1.0
    - 4.2.0
    - 4.2.2
    - 4.3.0
    - 4.3.1
    - 4.4.0
  - dependency-name: chai
    versions:
    - 4.3.2
- package-ecosystem: docker
  directory: "/frontend"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 4
  ignore:
  - dependency-name: node
    versions:
    - 15.9.0
- package-ecosystem: docker
  directory: "/backend"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 4
  ignore:
  - dependency-name: node
    versions:
    - 15.9.0
