frontend:
  - changed-files:
      - any-glob-to-any-file: frontend/**/*
backend:
  - changed-files:
      - any-glob-to-any-file: backend/**/*
infrastructure:
  - changed-files:
      - any-glob-to-any-file: [scripts/**/*, .github/**/*]
