FROM node:15.14.0

WORKDIR '/var/www/app'
# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)


COPY package*.json ./

RUN npm ci --only=production

RUN npm install -g serve

# If you are building your code for production

# Bundle app source
COPY . .
EXPOSE 3000
ENV NODE_ENV production
RUN npm run build
