# docker-compose.yml
version: "3"
services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/var/www/app
      # expose a named volume that works because installing
      # and then mounting will hide that folder, so we need to explicitly
      # show it again
      # note that when reinstalling modules, we need to remove this volume
      - fe_modules:/var/www/app/node_modules
    ports:
      - 3000:3000
    environment:
      # The port hooked up to the API 
      - REACT_APP_API_PORT=5000
      # Defines what port to use for development, i.e. localhost:$PORT for the frontend
      - PORT=3000
    command:
      sh -c 'npm start'

# explicitly defines the volumes so that docker-compose down -v will destroy them
volumes:
  fe_modules:

