#!/bin/bash
echo DB_URI=${DB_URI} > .env
echo GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID} >> .env
echo GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET} >> .env
echo SESSION_SECRET=${SESSION_SECRET} >> .env
echo CYPRESS_RECORD_KEY=${CYPRESS_RECORD_KEY} >> .env
