#!/bin/bash
echo DB_URI=${DB_URI} > .env
echo GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID} >> .env
echo GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET} >> .env
echo SESSION_SECRET=${SESSION_SECRET} >> .env
echo CYPRESS_RECORD_KEY=${CYPRESS_RECORD_KEY} >> .env
echo MAPQUEST_KEY=${MAPQUEST_KEY} >> .env
echo MAPQUEST_URI=${MAPQUEST_URI} >> .env 
echo REACT_APP_MAPBOX_ACCESS_TOKEN=${REACT_APP_MAPBOX_ACCESS_TOKEN} >> .env
echo REACT_APP_API_URI=${REACT_APP_API_URI} >> .env 
echo FE_URI=${FE_URI} >> .env 
