name: Cleanup Branch on Merge
on:
  pull_request:
    branches:
      - master
jobs:
  cleanup-branch:
    name: Delete the branch when the PR gets merged
    runs-on: ubuntu-latest
    steps:
    - uses: jessfraz/branch-cleanup-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
