name: FE/BE Testing

on: [push]

jobs:

  test-fe:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup CI Script 
      run: bash scripts/setup_ci.sh
    - name: Check successful frontend build 
      run: docker-compose run frontend npm run build
    - name: Check successful frontend render without crash
      run: docker-compose run -e CI=true frontend npm test
    

  test-be:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup CI Script 
      run: bash scripts/setup_ci.sh
    - name: Run backend tests 
      run: docker-compose run backend npm test
    
