name: FE/BE Testing

on: [push]

jobs:

  test-fe:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Check successful frontend build 
      run: docker-compose run frontend npm run build
    - name: Check successful frontend render without crash
      run: docker-compose run -e CI=true frontend npm test
    

  test-be:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run backend tests 
      env:
        DB_URI: mongodb://db:27017/LAH_DB
      run: docker-compose run backend npm test
