name: FE/BE Testing

on: [push]

jobs:

  test-fe:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup CI Script 
      run: bash scripts/setup_ci.sh
    - name: Build Docker Image
      run: docker build -t lah-frontend ./frontend
    - name: Check successful frontend NPM build 
      run: docker run lah-frontend npm run build
    - name: Check successful frontend render without crash
      run: docker run -e CI=true lah-frontend npm test
    
  cypress:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup CI Script 
      run: bash scripts/setup_ci.sh 
      env:
        DB_URI: ${{ secrets.TEST_DB_URI }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
    - name: Run Cypress Tests
      run: BYPASS_AUTH_ROLE=ADMIN docker-compose -f docker-compose.cypress.yml -f docker-compose.yml up --exit-code-from=cypress --abort-on-container-exit

  test-be:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup CI Script 
      run: bash scripts/setup_ci.sh
      env:
        DB_URI: ${{ secrets.TEST_DB_URI }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
    - name: Build Backend & Run Tests 
      run: docker-compose run -e CI=true backend npm test
    
