name: Labeler
on: [pull_request_target]
permissions:
  contents: read
  pull-requests: write
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      # No checkout or execution of PR code in a privileged workflow.
      - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5
