name: Whitespace
on: [push, pull_request]
permissions:
  contents: read
jobs:
  whitespace:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false
          fetch-depth: 2
      - run: git diff --check HEAD~1 HEAD
