name: Linting

on: [push]

jobs:
  format:
    name: Prettier Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x 
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Prettier check
      run: |
        npm install
        npm run prettier-check
      env:
        CI: true

  lint-frontend:
    runs-on: ubuntu-latest
    name: ESLint Frontend
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Lint frontend
        run: |
         npm install
         npm run lint:fe

  lint-backend:
    runs-on: ubuntu-latest
    name: ESLint Backend
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Lint backend
        run: |
         npm install
         npm run lint:be
