name: Linting

on: [push]

jobs:
  format:
    name: Prettier Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x 
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Prettier check
      run: |
        npm ci
        npm run prettier-check
      env:
        CI: true
