name: Node CI

on: [push]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x 
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Prettier check
      run: |
        npm install
        npm run prettier-check
      env:
        CI: true

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: npm run lint
        run: |
          cd frontend
          docker-compose run frontend npm run lint
