name: Testing

on: [push]

jobs:
  test-be:
    name: Backend Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup CI Script
        run: bash scripts/setup_ci.sh
        env:
          DB_URI: ${{ secrets.TEST_DB_URI }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
      - name: Build Backend & Run Tests
        run: docker-compose run -e CI=true backend npm test

  test:
    name: Cypress Run
    runs-on: ubuntu-16.04
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run 3 copies of the current job in parallel
        containers: [1, 2]
    steps:
      - uses: actions/checkout@v1
      - name: Setup CI Script
        run: bash scripts/setup_ci.sh
        env:
          DB_URI: ${{ secrets.TEST_DB_URI }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          MAPQUEST_KEY: ${{ secrets.MAPQUEST_KEY }}
          MAPQUEST_URI: ${{ secrets.MAPQUEST_URI }}
          REACT_APP_MAPBOX_ACCESS_TOKEN: ${{ secrets.REACT_APP_MAPBOX_ACCESS_TOKEN }}
          REACT_APP_API_URI: ${{ secrets.REACT_APP_API_URI }}
          FE_URI: ${{ secrets.FE_URI }}
      - name: Seed Test Database
        run: docker-compose run backend /bin/bash -c "node utils/generate_mock_data.js 100 false --color"
      # # Setup tmate for debugging
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v1
      - name: Build Stack
        run: docker-compose -f docker-compose.cypress.yml build
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          record: true
          parallel: true
          working-directory: frontend
          env: BASE_URI=http://localhost:3000,API_URI=http://localhost:5000
          start: docker-compose -f ../docker-compose.cypress.yml up -d
          wait-on: "http://localhost:3000"
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      